@startuml
'https://plantuml.com/sequence-diagram

title  Domain Model / As Product Manager or Financial director, I want to know the future cashflows for the upcoming n months filtered/broken down by plan

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    -username
    -password
    -photo
}

class DisplayRevenue{
   - String planName
   -List<RevenueData>
}
class RevenueData{
    - private String month;
    - private Double totalRevenue;
     -private String year;
}
class Role{
    -type
}


Role "1" <.right. "1" User: Has
User "1" .right.> "1" DisplayRevenue: Accesses
DisplayRevenue "1" .down.> "1" RevenueData: has


@enduml