@startuml
'https://plantuml.com/sequence-diagram
actor "Project Manager" as MD
title Software Design Document / As a Project Manager, I want to know the number of active subscriptions or canceled subscriptions in a specific month

activate MD
MD -> ":System" : GET dashboard/status
alt successful case - data is accepted
activate ":System"
":System" --> ":System" : Gets data from Database
":System" --> MD : Informs operation success
deactivate ":System"

end

alt failure case - data is not accepted
activate ":System"
":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml