@startuml
actor "Costumer" as MD

activate MD
MD -> ":System" : POST /subscriptions/create
":System" --> ":System" : Gets data from Post
":System" --> ":System" : Validates if plan exist locally or external
":System" --> ":System" : Validates if user exist locally or external
":System" --> ":System" : Validates if user has a subscription locally or external

alt successful case - data is accepted and validated
activate ":System"
":System" --> ":System" : Advance to create a subscription
":System" --> MD : Informs operation success

else failure case - data is not accepted

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
