@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Cancel  a new Subscription

autonumber

actor "Client" as Ac
participant ":User" as User
database ":UserDB" as Udb
participant ":Subscription" as Auth
database ":SubscriptionHTTP" as SHTTP
database ":SubscriptionDB" as SDB
participant ":Subscription1" as Serv

Ac->User: POST public/login
User->Udb:checkLocal
Udb-->User:user
User-->User:generates JWT Token
User-->Ac:200
Ac->Auth: PATCH /subscriptions/
Auth->SHTTP: cancel
alt Subscription exists in the first Instance
SHTTP->SDB:checkSubExists
SDB-->SHTTP:subscriptions
alt Subscription doesn´t exist in the first instance
SHTTP->Serv:GET subscriptions/external/{username}
Serv-->SHTTP:200
note left
If sub does not exist
SubsHTTP trows: User does not have sub
--
If sub exist in other machine
SubsHTTP trows: Sub can only be changed in other machine
end note
end
SHTTP-->Auth:sub

end
Auth->Auth:save
Auth-->Ac:200
@enduml