@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  title  Create  a new Subscription Bonus

autonumber

actor "Client" as Ac
participant ":PlanController" as PlanController
participant ":PlanService" as PService
participant ":PlanManager" as PManager
database ":PlanDB" as PDB

box "Subscriptions Component"
    participant ":SubService" as Service
    participant ":SubManager" as MG
    database "SubDB" as SDB
end box





participant ":MS Broker" as Broker

Ac->PlanController:POST  /plans/createBonus
PlanController->PService:createBonus(CreatePlanRequestBonus resource)
PService->PManager:findByNameDoesNotExists()
PManager->PDB:check if exist in DB
PDB-->PManager:empty
PManager-->PService:empty
PService->Broker:Publish(create_plan_bonus,CreatePlanRequestBonus planBonusName)


note right
Broker Notifies PlanQ and PlanC about the plan created
end note

PService<-Broker:consumes(create_plan_bonus,CreatePlanRequestBonus planBonusName)

PService->PService:save plan created
PService-->PlanController:plans

PlanController-->Ac:202

Broker->Service:consumes(create_plan_bonus,CreatePlanRequestBonus planBonusName)
Service->MG:findByUser(user)
MG->SDB:checks if exist in DB
SDB-->MG:empty
note right
No Subscription related with the user
Means it can create a Bonus Sub
end note
MG-->Service:empty
Service->Service:create Subscription
Service->Broker:publish (create_sub_bonus,CreateSubsByRabbitRequest subRequest)
Broker->Service:consumes(create_sub_bonus,CreateSubsByRabbitRequest subRequest)
note right
Broker Notifies SubsQ and SubsC about the plan created
end note








@enduml
