@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Sequence Diagram / Login account

autonumber

actor "User" as Ac
participant ":AuthApi" as Auth
participant ":Authentication" as Auth2
participant ":User" as User
participant ":JwtClaimsSet" as Jwt


Ac->Auth:POST public/login
Auth->Auth2:authenticate()
Auth2-->Auth:authentication
Auth->User:(User) authentication.getPrincipal()
User-->Auth:user
Auth->Jwt:JwtClaimsSet.builder()
Jwt-->Auth:claims
Auth-->Ac:ResponseEntity.ok()











@enduml