@startuml
'https://plantuml.com/sequence-diagram
actor "Marketing director" as MD

activate MD
MD -> ":System" : PATCH /subscriptions/change/{actualPlan}/{newPlan}
alt successful case - migration is accepted
activate ":System"
":System" --> ":System" : Advance to migrate all users of a certain plan to a different plan
":System" --> MD : Informs operation success

else failure case - migration is not accepted

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
