@startuml

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    -username
    -password
    -photo
}

class Subscriptions {
    -startDate
    -endDate
    -paymentType
    -activeStatus
}

class Plans{
    -name,
       - description
        - numberOfMinutes
        -maximumNumberOfUsers
        -musicCollection
         -musicSuggestion
         -annualFee
         -monthlyFee
         -active
         -promoted
}

class Role{
    -type
}


Role "1" <.right. "1" User: has
User "1" .right.> "1" Subscriptions: creates
Subscriptions "1" .right.> "1" Plans: has
@enduml
