@startuml
'https://plantuml.com/sequence-diagram
actor "New Costumer" as MD

activate MD
MD -> ":System" : POST /subscriptions/create
":System" --> ":System" : Gets data from Post
alt successful case - data is accepted
activate ":System"
":System" --> ":System" : Advance to create a subscription
":System" --> MD : Informs operation success

else failure case - data is not accepted

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
