@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Get Sub Plan Details

autonumber

actor "Client" as Ac

participant ":SubscriptionC" as SubC
participant ":SubscriptionQ" as SubQ
participant ":Message Broker" as Broker

Ac->SubC:PATCH subscriptions/

SubC->Broker: publish(subs_cancel,UpdateSubsRabbitRequest update)
SubC-->Ac:201

Broker->SubC:notify(subs_cancel,UpdateSubsRabbitRequest update)
SubC-->SubC:cancelSub(Subscriptions sub)
Broker->SubQ:notify(subs_cancel,UpdateSubsRabbitRequest update)
deactivate Broker

SubQ-->SubQ:cancelSub(Subscriptions sub)

@enduml
