@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Get Sub Plan Details

autonumber

actor "Client" as Ac

participant ":SubscriptionQ" as SubC
participant ":PlansQ" as SubQ
participant ":Message Broker" as Broker

Ac->SubC:GET subscriptions/

SubC->Broker: publish(get_planDetails,String planName)

Broker->SubQ:notify(get_planDetails,String planName)
SubQ-->SubQ: getPlanDetails

SubQ->Broker: publish(give_planDetails, PlanDetails details)
Broker->SubC:notify(give_planDetails, PlanDetails details)
SubC-->Ac:200
deactivate Broker

@enduml
