@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

autonumber

actor "Subscriber" as Ac
participant ":DeviceController" as Ctrl
participant ":DeviceService" as Serv
participant ":DeviceRepository" as Repo
participant ":Device" as Entity


Ac -> Ctrl : PUT /device/macAddress

Ctrl -> Serv :update(macAddress, resource, image, desiredVersion);


Serv -> Repo : device findByMacAddress_MacAddress(macAddress)
Repo --> Serv : device
note right
  if a device hasn't the
  same mac address
  has the one provided the code will
  end here and throw
  a EntityNotFoundException
end note

Serv -> Serv : Check if user can access this device

Serv -> Entity : update(desiredVersion, resource.getName(), resource.getDescription(), image)
Entity --> Serv : device

Serv -> Repo: save(device)

Repo --> Serv: device

Serv --> Ctrl: device

Ac <-- Ctrl : deviceView

@enduml
