@startuml
'https://plantuml.com/sequence-diagram
actor "Subscriber" as User
autonumber
autoactivate on
activate User

User ->  ":Api": PUT/device/{macAddress}
User <--  ":Api": request data(name, description, image)
User ->  ":Api": input requested data
":Api" --> User: informs operation (in)success


@enduml
