@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Deactivate  a  Plan

autonumber


actor "Client" as Ac
participant ":PlanC" as Auth
participant ":PlanQ" as Serv

participant ":Message Broker" as Broker


Ac->Auth:PATCH plans/deactivate/{name}
Auth->Auth:storePlan(Plan plan)
Auth-->Ac:200
Auth->Broker: publish(plans_to_update,PlanDetails plandetails)
Broker-->Serv:notify(plans_to_update,PlanDetails plandetails)
Serv->Serv:storePlan(Plan plan)













@enduml
