@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Deactivate  a  Plan

autonumber

actor "Client" as Ac
participant ":PlanQ" as Auth
participant ":PlanDB" as DB
Ac->Auth:GET /plans/
Auth->DB:findByNameDoesExists()
DB->DB:checkLocal
DB-->Auth:plan
Auth-->Ac:200
@enduml
