@startuml
'https://plantuml.com/sequence-diagram
actor "Subscriber" as MD

activate MD
MD -> ":System" : GET /subscriptions
":System" -> ":System" : Check if User exist in both machines
":System" -> ":System" : Check if User has subscription

alt successful case - user and subscription exists
activate ":System"
":System" --> ":System" : Gets data from database
":System" --> MD : Informs operation success


else failure case - subscription does not exist

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
