@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

autonumber

actor "Subscriber" as Ac
participant ":DeviceController" as Ctrl
participant ":DeviceService" as Serv
participant ":UserRepository" as UserRepo
participant ":SubscriptionRepository" as SubRepo
participant ":DeviceRepository" as Repo
participant ":CreateDeviceMapper" as Mapper


Ac -> Ctrl : POST /device

Ctrl -> Serv :create(CreateDeviceRequest resource, DeviceImage deviceImage);

Serv -> UserRepo :user = findById(userId)
UserRepo --> Serv : user
note right
  if the user isn't
  logged in
  the code will
  end here and throw
  a EntityNotFoundException
end note

Serv -> SubRepo :subscription = findByUser(user)
SubRepo --> Serv : subscription
note right
  if subscription not found
  for user logged in
  the code will
  end here and throw
  a EntityNotFoundException
end note

Serv -> Repo : device findByMacAddress_MacAddress(resource.getMacAddress())
Repo --> Serv : device
note right
  if a device has the
  same mac address
  has another the code will
  end here and throw
  a IllegalArgumentException
end note

Serv -> Mapper :Device obj  = create(subscription, resource)

Mapper --> Serv: obj

Serv -> Serv: obj.setDeviceImage(deviceImage)

Serv -> Repo: save(obj)

Repo --> Serv: obj

Serv --> Ctrl: obj
note left
 The controller here also
 creates an ResponseEntity
 to show the user the obj with
 "deviceViewMapper" as objView
end note
Ac <-- Ctrl : objView

@enduml
