@startuml
'https://plantuml.com/class-diagram
hide circle
class SubscriptionsRepository <<interface>>

class Subscriptions {
    -startDate
    -endDate
    -paymentType
    -activeStatus
    -plan
    -user
}



class SubscriptionsViewMapper{
    +toSubscriptionsView(Subscription subscriptions):SubscriptionsView
}
class SubscriptionsController{
    +renewAnualSubscription(final WebRequest request,final Strin auth):ResponseEntity<SubscriptionsView>
    }
class SubscriptionsService{
 +renewAnualSubscription(long desiredVersion, String auth):Subscriptions

}




interface SubscriptionsRepository
{
+findByActiveStatus_ActiveAndUser(Boolean true, String username): Optional<Subscriptions>
+save(S entity) : <S extends Subscriptions>
+getPlansFromOtherAPI(String name): HttpResponse<String>
+getUserFromOtherAPI(String name) : HttpResponse<String>
+getSubsFromOtherApi(String name,String auth) : HttpResponse<String>
}




SubscriptionsController ..> SubscriptionsService: uses >
SubscriptionsService ..> SubscriptionsRepository: uses >
SubscriptionsRepository ..> Subscriptions: < record
SubscriptionsController ..>SubscriptionsViewMapper: uses >
SubscriptionsController ..>SubscriptionsRepository: HTTP API Call <

@enduml


