@startuml
'https://plantuml.com/sequence-diagram
actor "subscriber" as MD

activate MD
MD -> ":System" : PATCH /subscriptions/

alt successful case - subscription exist
activate ":System"
":System" --> ":System" : Validates if user exist locally or external
":System" --> ":System" : Validates if user has a subscription locally or external
":System" --> ":System" : Advance to check if sub is activated

alt successful case - if user exists and haves a subscription activated
activate ":System"
":System" -> ":System" : Advance to deactivate the subscription
":System" --> MD : Informs operation success

else failure case - if user exists and his subscription is deactivate or if user does not exists

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
