@startuml
'https://plantuml.com/sequence-diagram
actor "subscriber" as MD

activate MD
MD -> ":System" : PATCH /subscriptions/

alt successful case - subscription exist
activate ":System"
":System" --> ":System" : Advance to cancel a subscription
":System" --> MD : Informs operation success


else failure case - subscription does not exist

":System" --> MD : Shows error message
deactivate ":System"
end
deactivate MD
@enduml
