@startuml
'https://plantuml.com/sequence-diagram
actor "Marketing Director" as MD
title Software Design Document/ As Marketing director, I want to define a new Plan detailing the monthly and annual cost, the maximum number of devices and other characteristics of the plan

activate MD
MD -> ":System" : POST /plans
":System" --> ":System" : Gets data from Post
":System" --> ":System" : Validates data
alt successful case - data is accepted
activate ":System"
alt HTPP  API CALL TO ANOTHER PLAN INSTANCE
":System" --> ":System" :Returns a  404
end
":System" --> ":System" : Advance to create a Plan

":System" --> MD : Informs operation success
deactivate ":System"

end

alt failure case - data is not accepted
activate ":System"
":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml