@startuml
'https://plantuml.com/sequence-diagram

actor "Project Manager/Financial director" as Ac
participant ":DashboardController" as Ctrl
participant ":DashboardService" as Serv
participant ":DashboardRepository" as Repo
participant ":PlansRepository" as RepoPlans
participant ":Plans" as Plans
participant ":CreateDashboardMapper" as Mapper
participant ":DashboardViewMapper" as View

Ac -> Ctrl: GET /currentRevenue
Ctrl -> Serv: getDashboardRevenueTillNow(String plan)
Serv -> Repo: getPaymentTypeAndPlanNameCounts(String startDate, String endDate)
note left
Search will create an object from Subscriptions
with planName, paymentType, startDate, and the number
of subscriptions for that plan.
end note
Repo --> Serv: results

Serv -> RepoPlans: findByName_Name(planName)
note left
Search will compare the planName from the obj
with the plan introduced by the user.
If it matches, it will return the revenue of
that plan; otherwise, it will return all revenues.
end note
RepoPlans --> Serv: planObj

alt (obj.paymentType == "monthly")
    Serv -> Plans: getMonthlyFee()
    Plans --> Serv: monthlyFee
else (obj.paymentType == "annually")
    Serv -> Plans: getAnnualFee()
    Plans --> Serv: annualFee
end

Serv -> Mapper: createRevenueTillNow(finalRevenue)
activate Mapper
Mapper --> Serv: obj
Serv --> Ctrl: obj
deactivate Serv
Ctrl -> View: toDashboardView(obj)
activate View
View --> Ctrl: dashboardView
deactivate View
Ctrl --> Ac: dashboardView

@enduml
