@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Change Subscription

autonumber

actor "Client" as Ac
participant ":SubscriptionController" as Auth
participant ":SubscriptionService" as SService
participant ":SubscriptionManager" as UManager
database ":SubsDB" as SDB
database ":SubsHTTP" as SDBHTTP

participant ":MS Broker" as Broker

Ac->Auth: PATCH /subscriptions/change/{planName}
Auth->SService: change

SService-> UManager: findPlanHttp
UManager->SDBHTTP:findPlanHttp
SDBHTTP-->UManager: plan
UManager-->SService: plan


SService->UManager: findSub
UManager->SDB: checkDataBase
SDB-->UManager:sub
UManager --> SService:sub
SService->Broker: publish
deactivate SService
SService -->Auth:sub
Auth --> Ac : 200
Broker-> SService: consumes
SService --> SService: change


@enduml
