@startuml
'https://plantuml.com/sequence-diagram
actor "Marketing Director" as MD
title Software Design Document / As marketing director, I want to deactivate a plan

activate MD
MD -> ":System" : PATCH /plans/deactivate/{name}
activate ":System"

":System" --> ":System" : Checks if Plan with that name exits

alt successful case - plan is exits
":System" --> ":System" : Checks if Plan is already deactivated or not


alt successful case - plan is activated
":System" --> ":System" : Deactivate the plan
":System" -> MD: Shows the Plan with deactivated settings
deactivate ":System"
end

alt failure case - plan is not activated

":System" --> MD : Tells the user plan is already deactivated
deactivate ":System"
end
deactivate ":System"
end


alt failure case - plan does not exist
activate ":System"
":System" --> MD : Tell user that plan does not exist
deactivate ":System"
end
deactivate MD
@enduml