@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Change details from  a  Plan

autonumber

actor "Client" as Ac
participant ":Plan" as Auth
participant ":Plan1" as Serv


Ac->Auth:PATCH plans/update/{name}
Auth->Auth:checkLocal

alt Plans exist locally
Auth->Auth:ChangeDetails
Auth->Auth:save
end
alt Plans exist on another instance
Auth->Serv: GET plans/external/{planName}
Serv-->Auth:200
Auth-->Auth:Throw error message

end
Auth-->Ac:200









@enduml