@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber


actor "Subscriber" as Ac
participant ":SubscriptionsController" as Ctrl
participant ":SubscriptionsService" as Serv
participant ":UserRepository" as UserRepo
participant ":SubscriptionsRepository" as SubRepo
participant ":Subscriptions" as Sub

Ac -> Ctrl : GET /subscriptions/
Ctrl -> Serv : Plan plan = planDetails()

Serv -> UserRepo :User user = userRepository.findById(Long.valueOf(newString))
UserRepo --> Serv : user

note right
  if the user who is trying to get the details
  does not exist in the system the code will
  end here and throw a UsernameNotFoundException
end note

Serv -> SubRepo :Optional <Subscriptions> subscription = repository.findByUser(user)
SubRepo --> Serv : subscription

note right
  if the user
  who is trying to subscribe
  already has a subscription,
  the code will
  end here and throw
  a IllegalArgumentException
end note


Serv -> Sub: Plan plan = subscription.getPlan()
Sub --> Serv: plan
Serv --> Ctrl: plan


note left
 The controller here also
 creates an ResponseEntity
 to show the user the plan with
 "plansViewMapper" as objView
end note
Ac <-- Ctrl : planView

@enduml
