@startuml
'https://plantuml.com/sequence-diagram
actor "Marketing Director" as MD
title Software Design Document/ As marketing director, I want to cease a plan
autonumber
autoactivate on
activate MD

MD -> ":Api" : DELETE /plans?name=
":Api" --> MD: informs operation (in)success


@enduml
