@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title   Delete Plan Bonus

autonumber
actor "Client" as Ac
box "Plan  Command Container"

participant ":PlanController" as PlanController
participant ":PlanService" as PService
participant ":PlanCOMSender" as PSender
participant ":PlanCOMReceiver" as PReceiver
participant ":PlanManager" as PManager
end box

box "Subscriptions Command Container"
    participant ":SubService" as Service
       participant ":SubscriptionCOMSender" as SSender

    participant ":SubManager" as MG
    participant ":SubscriptionCOMReceiver" as SReceiver
end box






participant ":MS Broker" as Broker

Ac->PlanController:POST  /plans/createBonus
PlanController->PService:createBonus(CreatePlanRequestBonus resource)
PService->PManager:findByNameDoesNotExists()
PManager->PManager:check if exist in DB
PManager-->PService:empty
deactivate PManager
PService->PSender:createBonus(resource)
PSender->Broker:Publish(create_plan_bonus,CreatePlanRequestBonus planBonusName)
PSender->Broker:Publish(send_plan_to_sub_bonus,CreatePlanRequestBonus planBonusName)

deactivate PSender
note right
Broker Notifies PlanQ and PlanC about the plan created
end note

PReceiver<-Broker:consumes(create_plan_bonus,CreatePlanRequestBonus planBonusName)
PReceiver->PService:storeBonusPlan
deactivate PReceiver


PService->PService:save plan created
deactivate PService


PService-->PlanController:plans


PlanController-->Ac:202
deactivate PService
Broker->Service:consumes(send_plan_to_sub_bonus,CreatePlanRequestBonus planBonusName)
Service->MG:findByUser(user)
MG->MG:checks if exists

note right
 Subscription related with the user
 It´s a BonuS. Throws error and
 Deletes PlanBonus
end note
MG-->Service:subscription
deactivate MG

Service->Service:throws error
Service->SSender:sendDelete(plansBonusName)
SSender->Broker:publish(delete_plan,String name)
note right
In the SubQ it consumes the delete_plan
in the SubsComReceiver and deletes in the
Subs service
end note
deactivate SSender
deactivate Service
deactivate Service
Broker->PReceiver:consumes(delete_plan,String name)
activate PService
PReceiver-->PService: deletePlanBonus(String plansBonus)
note right
Broker Notifies PlansQ and PlansC about the plan updated to delete
end note
PService->PManager:deleteByName(plansBonus)
PManager->PManager:delete plan in database
PManager-->PService:deleted Plan







@enduml
