@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Delete Plan Bonus in case Sub Bonus already exists

autonumber

actor "Client" as Ac
participant ":PlanC" as Auth
participant ":PlanQ" as Serv
box "Subscriptions Component"
    participant ":SubC" as NewComp
end box

participant ":Message Broker" as Broker


Ac->Auth:POST /plans/createBonus
Auth->Broker: publish(create_plan_bonus,CreatePlanRequestBonus planBonusName)

Auth-->Ac:202
Broker->Auth:consumes(create_plan_bonus,CreatePlanRequestBonus planBonusName)
Auth->Auth:storePlan(Plan plan)

Broker->Serv:consumes(plans_create,PlanDetails plandetails)


Serv->Serv:storePlan(Plan plan)
Broker->NewComp:consumes(create_plan_bonus,CreatePlanRequestBonus plansBonusName)
NewComp->NewComp:create
note right
If there is a Subscription
 bonus,it throws an error
end note
NewComp->Broker:publish(delete_plan,String name)
Broker->Auth:consumes(delete_plan,CreateSubsByRabbitRequest updatedSub)
Auth->Auth:deletePlanBonus
Broker->Serv:consumes(delete_plan,CreateSubsByRabbitRequest updatedSub)
Serv->Serv:deletePlanBonus












@enduml
