@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Sequence Diagram / As marketing director, I want to know the price change history of a plan

autonumber

actor "New Customer" as Ac
participant ":PlanController" as Ctrl
participant ":PlansService" as Serv
participant ":PlansRepository" as Repo
participant ":FeeRevisionViewMapper" as View

Ac -> Ctrl : GET /plans/history/{name}
Ctrl -> Serv :List<FeeRevisionView> list = history(string name)

Serv -> Repo :Optional<Plans> plan = findByName_Name(name)

Repo --> Serv: plan
note left
1) Service will check if plan exists

If 1 comes true,
Service will trow IllegalArgumentException
end note

Serv --> Serv : List<FeeRevision> list = plans.getFeeRevisions();

Serv -->Ctrl: list
Ctrl ->View: toFeesView(list)
View -->Ctrl: feeView
Ac <-- Ctrl : feeView

@enduml