@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

autonumber

actor "Subscriber" as Ac
participant ":DeviceController" as Ctrl
participant ":DeviceService" as Serv
participant ":UserRepository" as UserRepo
participant ":SubscriptionRepository" as SubRepo
participant ":DeviceRepository" as Repo


Ac -> Ctrl : GET /device/all

Ctrl -> Serv :findAllDevicesByUser();

Serv -> UserRepo :user = findById(userId)
UserRepo --> Serv : user
note right
  if the user isn't
  logged in
  the code will
  end here and throw
  a EntityNotFoundException
end note

Serv -> SubRepo :subscription = findByUser(user)
SubRepo --> Serv : subscription
note right
  if subscription not found
  for user logged in
  the code will
  end here and throw
  a EntityNotFoundException
end note

Serv -> Repo: findAllBySubscription(subscription)

Repo --> Serv: List<device>

Serv --> Ctrl: List<device>
note left
 The controller here also
 creates an ResponseEntity
 to show the user the obj with
 "deviceViewMapper" as objView
end note
Ac <-- Ctrl : List<deviceView>

@enduml
