@startuml
'https://plantuml.com/sequence-diagram
actor "Subscriber" as User
autonumber
autoactivate on
activate User

User ->  ":Api": GET/device/all
":Api" --> User: informs operation (in)success


@enduml
