@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

autonumber

actor "Subscriber" as Ac
participant ":DeviceController" as Ctrl
participant ":DeviceService" as Serv
participant ":DeviceRepository" as Repo


Ac -> Ctrl : DELETE /device/macAddress

Ctrl -> Serv :deleteDevice(macAddress, desiredVersion);


Serv -> Repo : device findByMacAddress_MacAddress(macAddress)
Repo --> Serv : device
note right
  if a device hasn't the
  same mac address
  has the one provided the code will
  end here and throw
  a EntityNotFoundException
end note

Serv -> Serv : Check if user can access this device

Serv -> Repo: deleteByIdIfMatches(device.getId(), desiredVersion)

Repo --> Serv:

Serv --> Ctrl:

Ac <-- Ctrl :

@enduml
