@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Create  a new Subscription

autonumber

actor "Client" as Ac
participant ":SubscriptionController" as Auth
participant ":SubscriptionService" as SService
participant ":SubscriptionManager" as UManager
database ":SubsDB" as SDB
participant ":PlanController" as Plan
participant ":PlanService" as PService
participant ":PlanManager" as PManager
database ":PlanDB" as PDB


participant ":MS Broker" as Broker

Ac->Auth: POST /subscriptions/create
Auth->SService: create
SService->Broker: publish
Broker->PService: notify
PService-> PManager: checkByName
PManager-> PDB: checkDataBase
PDB-->PManager:plan
PManager-->PService:plan
PService-->Broker: publish
Broker->SService:notify


SService->UManager:findSub
UManager->SDB: checkDataBase
SDB-->UManager:empty
UManager --> SService:empty
SService-->Broker: publish
SService -->Auth:sub
Auth --> Ac : 201
Broker-> SService: notify
SService --> SService: create


@enduml