@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Get Subscription plan details

autonumber

actor "Client" as Ac
   participant ":SubscriptionController" as Auth
    participant ":SubscriptionService" as SService
    participant ":SubscriptionManager" as UManager
    participant ":PlanManager" as PManager
    database ":SubsDB" as SDB
    database ":PlanDB" as PDB

Ac->Auth: GET /subscriptions/
Auth->SService: planDetails
SService->UManager: findSub
UManager->SDB: checkDataBase
SDB-->UManager:sub
UManager --> SService:sub

SService->PManager: findPlan
PManager-> PDB:checkDataBase
PDB-->PManager: planDetails
PManager-->SService:planDetails
SService --> SService: planDetails
SService -->Auth:planDetails
Auth --> Ac : 200

@enduml