@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Renew  a new Subscription

autonumber

actor "Client" as Ac
participant ":Subscription" as Auth
participant ":SubscriptionHTTP" as SHTTP
participant ":User" as User
participant ":UserDB" as UDB
participant ":User1" as User1
participant ":UserHTTP" as UHTTP
participant ":SubscriptionDB" as SDB
participant ":Subscription1" as Serv
participant ":Plan" as Plan
participant ":PlanDB" as PDB
participant ":Plan1" as Plan1
participant ":PlanHTTP" as PHTTP

Ac->Auth:  PATCH /subscriptions/change/{name}
Auth->SHTTP:
SHTTP->User:checkUserExists
alt User exist in first instance
User->UDB:checkLocal
UDB-->User:exists
alt User doesn´t exist in the first instance
User->User1:GET user/external/{name}
User1->UHTTP:checkInstance
UHTTP-->User1:200
User1-->User:200
end
User-->SHTTP:200

end

alt Subscription exists in the first Instance
SHTTP->SDB:checkSubExists
SDB-->SHTTP:subscriptions
alt Subscription doesn´t exist in the first instance
SHTTP->Serv:GET subscriptions/external/{username}
Serv-->SHTTP:200
SHTTP->SHTTP:ThrowIllegalMessage
end
SHTTP->Plan:GET /api/plans/{name}

alt Plan exist in the first instance
Plan->PDB:checkLocal
PDB-->Plan:200
alt Plan doesn´t exist in the first instance
Plan->Plan1:GET plans/external/{planName}
Plan1->PHTTP:checkInstance
PHTTP-->Plan1:200
Plan1-->Plan:200
end
end
Plan-->SHTTP:200
end
SHTTP-->Auth:changedSubscription

Auth->Auth:save
Auth-->Ac:200
@enduml