@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Sequence Diagram / As a new customer I want to know all existing plans

autonumber

actor "User" as Ac
participant ":UserBootstraper" as Ctrl

participant ":UserRepository" as Repo

Ac->Ctrl:Initiates the system
alt Loop
Ctrl->Repo:checks what user is required to be initialized
Repo-->Ctrl:Returns the user
end





@enduml