@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Sequence Diagram / Register a new account

autonumber

actor "User" as Ac
participant ":AuthApi" as Auth
participant ":UserService" as Serv
participant ":UserRepository" as Repo
participant ":UserEditMapper" as Mapper
participant ":PasswordEncoder" as Pass
participant ":UserViewMapper" as View

Ac->Auth:POST public/register
Auth->Serv:create(CreateUserRequest request)
Serv->Repo:findByUsername(request.getUsername())
Repo-->Serv:user2
Serv->Repo:getUserFromOtherAPI(request.getUsername())
Repo->Serv:HTTP 404
Serv->Mapper:create(request)
Mapper-->Serv:user
Serv->Pass:setPassword(passwordEncoder.encode(request.getPassword())
Pass-->Serv:pass
Serv->Repo:save(user)
Repo-->Serv:user
Serv-->Auth:user
Auth->View:toUserView(user)
View->Auth:UserView
Auth-->Ac:userView








@enduml