@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Sequence Diagram / As a new customer I want to know all existing plans

autonumber

actor "New Customer" as Ac
participant ":PlanController" as Ctrl
participant ":PlansService" as Serv
participant ":PlansRepository" as Repo
participant ":PlansViewMapper" as View
participant ":PlansMapperInverser" as ViewInverser
participant ":PlanRequest" as Request


Ac -> Ctrl : GET /plans
Ctrl -> Serv :Iterable<Plans> plans = findActive()

Serv -> Repo :Iterable<Plans> plans = findActive_Active(true)
Repo --> Serv: plansLocal
alt Check other Plan instance
Serv ->Repo: getPlansFromOtherAPI()
Repo-->Serv:HTPP 200
Serv -> Request : Planrequest newPlan
Request --> Serv: newPlan
Serv -> ViewInverser : toPlansView(newPlan)
ViewInverser --> Serv: Plan obj
end
Serv->Serv:addPlanToIterable(planLocal,obj)
Serv -->Ctrl: planslocal

Ctrl ->View: toPlansView(plans)
View -->Ctrl: plansView
Ac <-- Ctrl : plansView


@enduml