@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Sequence Diagram / As a new customer I want to know all existing plans

autonumber

actor "New Customer" as Ac
participant ":PlanController" as Ctrl
participant ":PlansService" as Serv
participant ":PlansRepository" as Repo
participant ":PlansViewMapper" as View
participant ":PlanRequest" as Request
participant ":PlansMapperInverser" as ViewInverser



Ac -> Ctrl : GET /plans
Ctrl -> Serv :Iterable<Plans> plans = findActive()

Serv -> Repo :Iterable<Plans> plans = findActive_Active(true)
Repo --> Serv: plansLocal
alt Check other Plan instance
Serv ->Repo: addLocalPlusNot(planslocal)

Repo ->Repo: getPlansFromOtherAPI()
Repo -> Request : Planrequest newPlan
Request --> Repo: newPlan
Repo -> ViewInverser : toPlansView(newPlan)
ViewInverser --> Repo: Plan obj
Repo-->Repo:addPlanToIterable(planslocal, obj)
Repo-->Serv:plans
end
Serv -->Ctrl: plans

Ctrl ->View: toPlansView(plans)
View -->Ctrl: plansView
Ac <-- Ctrl : plansView


@enduml