@startuml
'https://plantuml.com/sequence-diagram
actor "new Customer" as MD
title  Software Design Document / As a new customer I want to know all existing plans

activate MD
MD -> ":System" : GET /plans
":System" --> ":System" : Gets data from databases
alt API HTPP call to another instance
":System"-->":System":Returns all plans in the other machine
end
":System" -> MD: Shows all saved plans

deactivate MD
@enduml