@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Deactivate a Plan

autonumber

actor "Client" as Ac
participant ":User" as User
database ":UserDB" as Udb

participant ":Plan" as Plan
database ":PlanDB" as PDB
database ":PlanHTTP" as PHTTP
participant ":Plan1" as Plan1
database "Plan1DB" as PDB1


Ac->User: POST public/login
User->Udb:checkLocal
Udb-->User:user
User-->User:generates JWT Token
User-->Ac:200
Ac->Plan:PATCH plans/deactivate/{name}
Plan->PDB:checkLocal
PDB-->Plan:plan
alt plan exists
Plan->Plan:Deactivate
Plan->Plan:save

end

alt plan isEmpty
Plan->PHTTP:GET plans/external/{planName}
PHTTP->Plan1:checkInstance
Plan1->PDB1:checkLocal

PDB1-->Plan1:200
deactivate PDB1

Plan1-->PHTTP:200
PHTTP-->Plan:200
end

Plan-->Ac:200
note right
If alt "plan inEmpty" is true
Plan trows: Plan exist in other machine
end note



@enduml