@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Create  a  Plan

autonumber

actor "Client" as Ac
participant ":User" as User
participant ":UserDB" as Udb

participant ":Plan" as Plan
database ":PlanDB" as PDB
database ":PlanHTTP" as PHTTP
participant ":Plan1" as Plan1
database "Plan1DB" as PDB1




Ac->User: POST public/login
User->Udb:checkLocal
Udb-->User:user
User-->User:generates JWT Token
User-->Ac:200
Ac->Plan:GET  /plans
Plan->PDB:checkLocal
PDB-->Plan:plansLocal

Plan->PHTTP:GET plans/external/
PHTTP->Plan1:checkInstance
Plan1->PDB1:checkLocal

PDB1-->Plan1:200
deactivate PDB1
Plan1-->PHTTP:200
PHTTP-->PHTTP:addPlans(plansLocal)

PHTTP-->Plan:plans

Plan-->Ac:200




@enduml