@startuml
'https://plantuml.com/sequence-diagram
actor "Subscriber" as MD

activate MD
MD -> ":System" : PATCH /subscriptions/renew
alt successful case -renew is accepted
activate ":System"
":System" --> ":System" : Advance to renew annual subscription
":System" --> MD : Informs operation success

else failure case - renew is not accepted

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
