@startuml
'https://plantuml.com/sequence-diagram
actor "Subscriber" as User
autonumber
autoactivate on
activate User

User ->  ":Api": DELETE/device/{macAddress}
":Api" --> User: informs operation (in)success


@enduml
