@startuml
'https://plantuml.com/sequence-diagram
actor "Marketing Director" as MD
title Software Design Document/ As marketing director, I want to change the pricing of a plan

activate MD

MD -> ":System" : PATCH /plans/updateMoney/{name}
":System" --> ":System" : Gets data from Patch

alt successful case - data is accepted

":System" --> ":System" : Checks if Plan exists
alt successful case - Plan exists
":System" --> ":System" : Apply data on plan
":System" --> MD : Tells users plan haves been updated and shows it
end
alt successful case - Plan does not exists
":System" --> MD : Tells user plan does not exists
end
end



alt failure case - data is not accepted
activate ":System"
":System" --> MD : Shows error message

end
deactivate MD
@enduml