@startuml
'https://plantuml.com/sequence-diagram
actor "Subscriber" as MD

activate MD
MD -> ":System" : PATCH /subscriptions/change/{name}
alt successful case - upgrade/downgrade plan is accepted
activate ":System"
":System" --> ":System" : Advance to upgrade/downgrade to specified plan
":System" --> MD : Informs operation success

else failure case - upgrade/downgrade is not accepted

":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml
