@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Change Plan details

autonumber

actor "Client" as Ac
participant ":User" as User
participant ":UserDB" as Udb

participant ":Plan" as Plan
participant ":PlanDB" as PDB
participant ":PlanHTTP" as PHTTP
participant ":Plan1" as Plan1



Ac->User: POST public/login
User->Udb:checkLocal
Udb-->User:user
User-->User:generates JWT Token
User-->Ac:200
Ac->Plan:PATCH plans/update/{name}
Plan->PDB:checkLocal
PDB-->Plan:plan
alt plan exists
Plan->Plan:ChangeDetails
Plan->Plan:save

end

alt plan isEmpty
Plan->PHTTP:GET plans/external/{planName}
PHTTP->Plan1:checkLocal
Plan1-->PHTTP:200
PHTTP->Plan1:PATCH plans/update/{name}
Plan1->PHTTP:200
PHTTP-->Plan:200
end
Plan-->Ac:200




@enduml