@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title  Create  a  Plan

autonumber

actor "Client" as Ac
participant ":User" as User
database ":UserDB" as Udb

participant ":Plan" as Plan
participant ":PlanDB" as PDB
database ":PlanHTTP" as PHTTP
participant ":Plan1" as Plan1



Ac->User: POST public/login
User->Udb:checkLocal
Udb-->User:user
User-->User:generates JWT Token
User-->Ac:200
Ac->Plan:POST  /plans
Plan->PDB:checkLocal
PDB-->Plan:empty
note left
If plan with name "planName"
exists locally
Plan trows: Plan with that name already exists
end note
Plan->PHTTP:GET plans/external/{planName}
PHTTP->Plan1:checkLocal
Plan1-->PHTTP:empty
PHTTP-->Plan:404
note left
If plan with name "planName"
exists not locally
Plan trows: Plan with that name already exists
end note
Plan->Plan:save
Plan-->Ac:201




@enduml