@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title Sequence Diagram/ As Marketing director, I want to define a new Plan detailing the monthly and annual cost, the maximum number of devices and other characteristics of the plan

autonumber

actor "Marketing Director" as Ac
participant ":PlanController" as Ctrl
participant ":PlansService" as Serv
participant ":PlansRepository" as Repo

participant ":CreatePlansMapper" as Mapper
participant ":PlansViewMapper" as View




Ac -> Ctrl : POST /plans
Ctrl -> Serv :Plans plans = create(CreatePlanRequest resource)
Serv -> Repo :Optional<Plans> plans = findByName_Name(resource.getName())
Repo --> Serv : plans.isEmpty
Serv->Repo:createNotLocal(auth,resource))
Repo->Repo:getPlansFromOtherAPI(resource.getName(),auth)
Repo->Repo:HTPP 404
Repo->Mapper:createPlansMapper.create(resource)
Mapper-->Repo:Plan obj;
Repo-->Serv:obj

note left
1) Service will check if plan exists

If 1 comes true,
Service will trow
IllegalArgumentException

2)Server does and HTTP call
to another plan instance
If it doesn´t exist on the other instance
Returns 404
end note

Serv -> Repo: save(obj)
Repo --> Serv: plan
Serv --> Ctrl: plan
Ctrl ->View: toPlansView(plan)
View -->Ctrl: planView
Ac <-- Ctrl : planView

@enduml