@startuml
'https://plantuml.com/sequence-diagram

title  Domain Model / As a Project Manager, I want to know the number of active subscriptions or canceled subscriptions in a specific month

skinparam classAttributeIconSize 0
hide circle
hide methods

class User{
    -username
    -password
    -photo
}

class Dashboard{
    -totalActiveSubscriptions
    - totalCanceledSubscriptions
}

class Role{
    -type
}


Role "1" <.right. "1" User: Has
User "1" .right.> "1" Dashboard: Accesses

@enduml