@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title Sequence Diagram / As a Project Manager, I want to know the number of active subscriptions or canceled subscriptions in a specific month

autonumber

actor "Project Manager" as Ac
participant ":DashboardController" as Ctrl
participant ":DashboardService" as Serv
participant ":DashboardRepository" as Repo
participant ":CreateDashboardMapper" as Mapper
participant ":DashboardViewMapper" as View


Ac -> Ctrl : Get /dashboard
alt Depending on url
Ctrl -> Serv :getDashboardView(int year,int month,boolean onlyActive,boolean onlyCancelled,String startDate,String endDate)
Ctrl -> Serv :getTotalNewSubscriptionsByDate(int year,int month,boolean onlyActive,boolean onlyCancelled,String startDate,String endDate)
Ctrl -> Serv :getTotalNewSubscriptions(int year,int month,boolean onlyActive,boolean onlyCancelled,String startDate,String endDate)
Ctrl -> Serv :getTotalCancelledSubscriptions(int year,int month,boolean onlyActive,boolean onlyCancelled,String startDate,String endDate)
Ctrl -> Serv :getTotalCancelledSubscriptionsByDate(int year,int month,boolean onlyActive,boolean onlyCancelled,String startDate,String endDate)

end
Serv -> Repo :findTotalActiveSubscriptions(String startDate,String endDate)
Repo --> Serv: activeSubscription
Serv -> Repo :findTotalCanceledSubscriptions(String startDate,String endDate)
Repo --> Serv: canceledSubscription
alt Depending on url
Serv -> Mapper :Dashboard obj  = create(Integer active, Integer canceled)
Mapper --> Serv: obj

Serv -> Mapper :Dashboard obj  = createActive(Integer active)
Mapper --> Serv: obj

Serv -> Mapper :Dashboard obj  = createCancelled(Integer cancelled)
Mapper --> Serv: obj

end

Serv -->Ctrl: dashboard
Ctrl ->View: toDahboardView(dashboard)
View -->Ctrl: dashboardView

Ac <-- Ctrl : show dashboard

@enduml