@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber
title   Renew a  Subscription

autonumber

actor "Client" as Ac
participant ":Subscription" as Auth
participant ":Subscription1" as Serv


Ac->Auth:  PATCH /subscriptions/renew
Auth->Auth:checkLocal
alt Subscription exist locally
Auth-->Auth:add a year
Auth-->Auth:save
end
alt Subscription doesn´t exist locally

Auth->Serv: GET /subscriptions/external/{username}
Serv-->Auth:200
Auth-->Auth:Throw error message
end
Auth-->Ac:200
@enduml