@startuml
'https://plantuml.com/sequence-diagram
actor "Project Manager/Financial director" as MD
title Software Design Document / As Product Manager or Financial director, I want to know the future cashflows for the upcoming n months filtered/broken down by plan

activate MD
MD -> ":System" : GET dashboard/revenuePlan
alt successful case - data is accepted
activate ":System"
":System" --> ":System" : Gets data from Database
":System" --> MD : Informs operation success
deactivate ":System"

end

alt failure case - data is not accepted
activate ":System"
":System" --> MD : Shows error message
deactivate ":System"

end
deactivate MD
@enduml