@startuml
'https://plantuml.com/sequence-diagram
actor "User" as MD
title  Software Design Document / As a new customer I want to know all existing plans

activate MD
MD -> ":System" : POST public/register
":System" --> ":System" : Gets data from Post
":System" --> ":System" : Validates data
alt successful case - data is accepted
activate ":System"
alt HTPP  API CALL TO ANOTHER USER INSTANCE
":System" --> ":System" :Returns a  404
end
":System" --> ":System" : Advance to create a User

":System" --> MD : Informs operation success
deactivate ":System"

end
":System" -> MD: Shows user

deactivate MD
@enduml